# Generated by Django 5.0.3 on 2024-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
